# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: DnD Chronicles
email: marques.s.arthur@gmail.com
description: >
  Homebrew & Campaign Diary
tagline: Mâb le i nagor, Bâd gurth vi ngalad firiel.
date: false
baseurl: "/cronicas-rpg" # the subpath of your site, e.g. /blog
url: "http://johncoene.github.io" # the base hostname & protocol for your site, e.g. http://example.com
author: Arthur Marques


# SEO
twitter:
  username: Marques_Art

logo: /assets/logo.png

lang: en


social:
  name: Arthur Marques
  links:
    - https://twitter.com/Marques_Art

# Build settings
exclude: README.md
markdown: kramdown
theme: jekyll-theme-cayman
gems:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
plugins_dir:
  - jekyll-roman
  - jekyll-seo-tag
